language: python
cache: pip
python: 3.5

env:
    - TOXENV=flake8
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35

matrix:
    fast_finish: true

    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7-dev
          env: TOXENV=py37
        - python: pypy-5.4
          env: TOXENV=pypy_54

    allow_failures:
        - env: TOXENV=py37
        - env: TOXENV=pypy_54

install:
    - pip install tox codecov

script:
    - tox

after_success:
    - codecov

notifications:
    email: false
